//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bittrex.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bittrex.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/market/buylimit.
        /// </summary>
        public static string BuylimitPath {
            get {
                return ResourceManager.GetString("BuylimitPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/market/cancel.
        /// </summary>
        public static string CancelPath {
            get {
                return ResourceManager.GetString("CancelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/account/getbalance.
        /// </summary>
        public static string GetbalancePath {
            get {
                return ResourceManager.GetString("GetbalancePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/account/getbalances.
        /// </summary>
        public static string GetbalancesPath {
            get {
                return ResourceManager.GetString("GetbalancesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/public/getcurrencies.
        /// </summary>
        public static string GetcurrenciesPath {
            get {
                return ResourceManager.GetString("GetcurrenciesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/account/getdepositaddress.
        /// </summary>
        public static string GetdepositaddressPath {
            get {
                return ResourceManager.GetString("GetdepositaddressPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/account/getdeposithistory.
        /// </summary>
        public static string GetdeposithistoryPath {
            get {
                return ResourceManager.GetString("GetdeposithistoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/public/getmarkethistory.
        /// </summary>
        public static string GetmarkethistoryPath {
            get {
                return ResourceManager.GetString("GetmarkethistoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/public/getmarkets.
        /// </summary>
        public static string GetmarketsPath {
            get {
                return ResourceManager.GetString("GetmarketsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/public/getmarketsummaries.
        /// </summary>
        public static string GetmarketsummariesPath {
            get {
                return ResourceManager.GetString("GetmarketsummariesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/public/getmarketsummary.
        /// </summary>
        public static string GetmarketsummaryPath {
            get {
                return ResourceManager.GetString("GetmarketsummaryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/market/getopenorders.
        /// </summary>
        public static string GetopenordersPath {
            get {
                return ResourceManager.GetString("GetopenordersPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/public/getorderbook.
        /// </summary>
        public static string GetorderbookPath {
            get {
                return ResourceManager.GetString("GetorderbookPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/account/getorderhistory.
        /// </summary>
        public static string GetorderhistoryPath {
            get {
                return ResourceManager.GetString("GetorderhistoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ttps://bittrex.com/api/v1.1/account/getorder.
        /// </summary>
        public static string GetorderPath {
            get {
                return ResourceManager.GetString("GetorderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/public/getticker.
        /// </summary>
        public static string GettickerPath {
            get {
                return ResourceManager.GetString("GettickerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/account/getwithdrawalhistory.
        /// </summary>
        public static string GetwithdrawalhistoryPath {
            get {
                return ResourceManager.GetString("GetwithdrawalhistoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/market/selllimit.
        /// </summary>
        public static string SelllimitPath {
            get {
                return ResourceManager.GetString("SelllimitPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/public/getmarketsummary.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://bittrex.com/api/v1.1/account/withdraw.
        /// </summary>
        public static string WithdrawPath {
            get {
                return ResourceManager.GetString("WithdrawPath", resourceCulture);
            }
        }
    }
}
